### PR TITLE
git: worktree, Fix file reported as `Untracked` while it is committed

### LINKED ISSUE #119: File reported as Untracked while it is commited (i.e. Unmodified)
Assuming my full path to repo is `/Users/panteliskaramolegkos/myrepo`, I am going through the following steps to check the status of a specific file (code below is part of a specific function)

```
	repo, err := git.PlainOpen(fullPathToRepo)
	if err != nil {
		return false, fmt.Errorf("ERROR: Unable to open repository %s\n%s", fullPathToRepo, err)
	}

	workTree, err := repo.Worktree()
	if err != nil {
		return false, fmt.Errorf("ERROR: Unable to open worktree for repository %s\n%s", fullPathToRepo, err)
	}
	workTreeStatus, err := workTree.Status()
	if err != nil {
		return false, fmt.Errorf("ERROR: Unable to retrieve worktree status for repository %s\n%s", fullPathToRepo, err)
	}
	fmt.Printf("%q\n", workTreeStatus.File("relative/path/to/file.yaml").Worktree)
	fmt.Printf("%q\n", workTreeStatus.File("/Users/panteliskaramolegkos/full/path/to/file.yaml").Worktree)
```

In both cases (i.e. using full or relative path, the following gets printed out

```
'?'
'?'
```

According to the [documentation](https://pkg.go.dev/github.com/go-git/go-git/v5@v5.1.0?tab=doc#StatusCode), this corresponds to status `Untracked`

However the file is committed (and pushed to the remote, but I guess this is irrelevant)

### PR DESCRIPTION
**Pull request by rodrigocam**
## Overview

When using the lib I have also faced this problem #119. After looking into the code my understanding is that we were initializing the `status` empty before making the diff operations. This causes an empty status object when no diff is encountered. Which lead us to get `Untracked` status for committed files.

I manage to solve this by adding an initialization method for our `status` that iterates over the `storer` index building an initial status with all the unmodified files included. This way, when we use `status.File` it will find it on the map and will return correctly the `Unmodified` status.

Fix #119

### CODE REVIEW

File: worktree_status.go [hunk 1]
```diff
@@ -47,8 +47,45 @@ func (w *Worktree) Status() (Status, error) {
...
+			if err != nil {
+				return nil, err
+			}
+			nodes = append(nodes, children...)
+			continue
+		}
+		fs := status.File(node.Name())
+		fs.Worktree = Unmodified
+		fs.Staging = Unmodified
+	}
```
Comment (pjbgf) [inline worktree_status.go:79]: This may have a performance impact, as we need to go through all nodes while growing `nodes` as part of that process.

What if instead, we amended `File(path string)` to validate the returning [s[path]](https://github.com/go-git/go-git/blob/master/status.go#L20) and force a default value of `Unmodified` if no value was currently set?

Comment (rodrigocam) [reply worktree_status.go:79]: Sorry, I didn't understand what you proposed. Can you explain it a little more?

Comment (pjbgf) [reply worktree_status.go:79]: The issue here is that going through the entire worktree to create an initial state as unmodified can be quite costly - specially on large repositories. I tested this on a mid-sized repository and noticed that with these changes the `.Status()` call took ~30% longer than before.

My initial suggestion was to amend `Status` so that the `File` func would effectively do the same thing as the pre-init you created. However, this won't really work in some cases, as when there are no changes the `Status` returns an empty list. Besides, the existing logic is incorrect as whatever file we pass on to `status.File(path)` it returns `Untracked` even if that file does not exist across both the staging and the worktree.

In order to fix this, while keeping backwards compatibility and not introducing a performance regression, I think we have a few options:
a) Introduce a new `Worktree.StatusWithOptions()` func which returns a new type that is more flexible and calculates the status of a given file on demand. I suspect this will need to have access to the worktree fs, so that it can handle the scenario I mentioned above, without needing to front-load the entire worktree. It may also need access to the exclusion rules.
b) Introduce a new `Worktree.StatusWithOptions()` func which returns a new type that is more flexible, but simply adds an option so users can opt-in to the front-loading this PR currently introduces.
c) Introduce a new `Worktree.FileStatus()` func which calls `.Status` and ensure the given file is correctly loaded to the Status map.

What are your thoughts on the above?

**Review by pjbgf — APPROVED** [review]
@rodrigocam thank you for working on this. I made some of the API changes we discussed before for improved extensibility, otherwise LGTM.
