### PR TITLE
git: worktree, don't delete untracked files on HardReset / Force checkout

### LINKED ISSUE #796: git.Worktree.Checkout with Force = true: behavior change in v5.7.0 (ignored files deleted)
Our team has noticed a behavior change when upgrading from go-git v5.6.1 to v5.7.0 regarding the usage of `Checkout()` and the `Force: true` option.

In v5.6.1 and previous versions, if the current branch had any ignored files (.gitignore) and we used the `Force: true` option when checking out another branch, the ignored files were left in place.

In v5.7.0, using `Force: true` option, files that are untracked AND ignored are all deleted from the filesystem after branch switch with `Checkout()`.

We have fixed the issue by using the option `Keep: true` instead of using the `Force` option, and now our ignored files are left alone on filesystem after switch of branches.

We did not know if we were incorrectly using `Force` to accomplish this before and a bug had been fixed in v5.7.0, or if this is not intended and a new bug has been introduced? If someone could confirm?

Example:
(Assume the current worktree directory has an ignored file that exists, and we are on a branch different than "test-branch")
```go
resultErr := w.Checkout(&git.CheckoutOptions{
    Branch: plumbing.NewBranchReferenceName("test-branch"),
    Force:   true})
```
in v5.6.1 and previous, the ignored file will be left alone, in v5.7.0 it will be deleted.

### PR DESCRIPTION
**Pull request by AriehSchneier**
## Summary

`Checkout` with `Force: true` (and `Reset` in `HardReset` mode) was deleting untracked files from the worktree. Real `git checkout -f` and `git reset --hard` never remove untracked files -- only `git clean -f` does.

Fixes #796, #1719, #365, and #633 (HardReset / Force checkout path).

### Root cause

`resetWorktree` computed a reverse diff between the worktree filesystem and the index (`diffStagingWithWorktree(reverse=true)`). A `Delete` action in this diff means "file exists on disk but is not in the index" -- covering both:

1. A tracked file deleted from the new target tree -- should be removed.
2. An untracked file -- must not be removed.

Previously all `Delete` actions were processed, so untracked files were deleted.

### Fix -- matching real git

Real `git reset --hard` / `git checkout -f` operates in three phases on tracked-file sets only:

1. **Tree-to-tree diff** (`fromTree -> toTree`): delete files tracked in `fromTree` but removed in `toTree`. Untracked files are invisible to this diff.

2. **Index-to-worktree**: write files in the new index but absent or stale on disk. `Delete` actions (file on disk, absent from the index node tree) are always truly untracked -- `SkipWorktree` entries are marked `skip=true` in the merkletrie and invisible to this diff, never surfaced as Delete actions here.

3. **SkipWorktree cleanup**: iterate all index entries directly; for any entry with `SkipWorktree=true` that still exists on disk, remove it. `diffStagingWithWorktree` never surfaces these as Delete actions (see phase 2). Untracked files in the same directories are untouched.

This PR introduces `diffTrees` and a new `resetWorktreeToTree` implementing this three-phase approach for `HardReset`. The old `resetWorktree` (used by `MergeReset`) is unchanged.

### Also fixed: `Index.SkipUnless`

`Index.SkipUnless` only ever set `SkipWorktree=true` for newly-excluded files but never cleared it for files moving back into the active set. Fixed by also setting `SkipWorktree=false` for included entries.

### Tests added

- `TestCheckoutForceUntracked` -- `Checkout{Force: true}` must not delete an untracked file.
- `TestPullAfterShallowClone_UntrackedFilesPreserved` -- untracked file must survive a subsequent `Pull`.
- `TestCheckoutForceSparseUntrackedPreserved` -- switching `SparseCheckoutDirectories` with `Force: true` must (a) remove tracked files outside the new sparse set from disk and (b) preserve untracked files inside those directories.

### CODE REVIEW

**Comment by onee-only** [comment]
Possibly related: https://github.com/go-git/go-git/issues/365, https://github.com/go-git/go-git/issues/1031, https://github.com/go-git/go-git/issues/633

**Comment by AriehSchneier** [comment]
> #365, #1031, #633

Added #365 and #633 as fixed, but for #1031 the untracked-files-deleted bug described in the body is fixed, but the actual feature request (Keep mode on ResetOptions) is a separate enhancement not addressed here

File: worktree.go [hunk 1]
```diff
@@ -501,6 +513,109 @@ func inFiles(files map[string]struct{}, v string) bool {
...
+		if errors.Is(err, plumbing.ErrReferenceNotFound) {
+			return nil, nil
+		}
+		return nil, err
+	}
+	c, err := w.r.CommitObject(head.Hash())
+	if err != nil {
+		return nil, err
+	}
+	return c.Tree()
```
Comment (onee-only) [inline worktree.go]:
```suggestion
	return w.r.getTreeFromCommitHash(head.Hash())
```
Could be simplified to this.

File: worktree_test.go [hunk 2]
```diff
@@ -344,6 +344,70 @@ func (s *WorktreeSuite) TestPullAfterShallowClone() {
...
+
+	// The untracked file must survive the pull (mirrors real git behaviour).
+	_, statErr := os.Stat(untrackedPath)
+	s.NoError(statErr, "untracked file was removed by pull (no Force) on a shallow clone")
+
+	// Push another commit and test with Force: true.
+	_ = CommitNewFile(s.T(), remote, "File5")
+
+	// Re-create the untracked file in case it was removed.
+	s.Require().NoError(os.WriteFile(untrackedPath, []byte("do not delete me"), 0o644))
```
Comment (pjbgf) [inline worktree_test.go]: Seems redundant - the untracked should fail on `L390`.

```suggestion
```

File: worktree_test.go [hunk 3]
```diff
@@ -344,6 +344,70 @@ func (s *WorktreeSuite) TestPullAfterShallowClone() {
...
+	err = w.Pull(&PullOptions{
+		RemoteName:    DefaultRemoteName,
+		SingleBranch:  true,
+		ReferenceName: plumbing.NewBranchReferenceName("master"),
+	})
+	s.Require().NoError(err)
+
+	// The untracked file must survive the pull (mirrors real git behaviour).
+	_, statErr := os.Stat(untrackedPath)
+	s.NoError(statErr, "untracked file was removed by pull (no Force) on a shallow clone")
```
Comment (pjbgf) [inline worktree_test.go]:
```suggestion
	s.Require().NoError(statErr, "untracked file was removed by pull (no Force) on a shallow clone")
```

File: worktree.go [hunk 4]
```diff
@@ -501,6 +513,109 @@ func inFiles(files map[string]struct{}, v string) bool {
...
+	}
+	b := newIndexBuilder(idx)
+
+	for _, ch := range worktreeChanges {
+		a, err := ch.Action()
+		if err != nil {
+			return err
+		}
+		if a == merkletrie.Delete {
+			// File is on disk but not in new index = untracked. Never delete.
```
[the remark this answers is not in the document]
Comment (pjbgf) [reply worktree.go]: Let's add a test case that caters for `untracked` file on a dir that is being removed from `SparseCheckoutDirectories`. Upstream carries on with the operation but shows a warning:

```
$ git sparse-checkout init
$ git sparse-checkout set plumbing
$ touch plumbing/abc2
$ git sparse-checkout set _examples
$ git s
On branch main
Your branch is behind 'origin/main' by 4 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

You are in a sparse checkout with 18% of tracked files present.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	plumbing/abc2
```

**Comment by AriehSchneier** [comment]
@pjbgf Updated and rebased (the new test found an existing bug which I also fixed)
