### PR TITLE
git: worktree_status, fix adding dot slash files to working tree (backported to v5). Fixes #1150

### LINKED ISSUE #1150: Unexpect behavior when adding dot slash files to working tree
When using git in a shell to add a file to the working tree, the same file can be added in different ways. One way it can be added is by adding the bare filename:

```shell
$ git add my-file
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   my-file
```

Another way it can be added is by prefixing the filename with dot slash:

```shell
$ git add ./my-file
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   my-file
```

These both produce the same staged file to be added to the working tree.

However, when adding a file to the working tree using `go-git`, the same file is stored with a different value in the git index. For example, adding the bare filename:

```go
gitRepo, _ := git.PlainOpen("my-repo")
gitWorktree, _ := gitRepo.Worktree()
gitWorktree.Add("my-file")
```

Produces the expected staged file in the working tree:

```shell
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   my-file
```

But if the file is added with the prefixed dot slash:

```go
gitRepo, _ := git.PlainOpen("my-repo")
gitWorktree, _ := gitRepo.Worktree()
gitWorktree.Add("./my-file")
```

A different file is staged:

```shell
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        new file:   ./my-file
```

I thought that it might have something to do with the shell expanding the dot slash but that doesn't seem to be the case since I tried adding the dot slash prefixed file using single quotes (`git add './my-file'`) and got the same result.

To me, this is unexpected behavior with git. Is that indeed the case or am I missing something?

### PR DESCRIPTION
**Pull request by BeChris**

### CODE REVIEW

File: worktree_status.go [hunk 1]
```diff
@@ -371,7 +371,7 @@ func (w *Worktree) doAdd(path string, ignorePattern []gitignore.Pattern, skipSta
 	}
 
 	if err != nil || !fi.IsDir() {
-		added, h, err = w.doAddFile(idx, s, path, ignorePattern)
+		added, h, err = w.doAddFile(idx, s, filepath.Clean(path), ignorePattern)
```
Comment (pjbgf) [inline worktree_status.go:374]: Please update this to `path = filepath.Clean(path)` above the `if`, as per change against `v6-exp`.

Comment (BeChris) [reply worktree_status.go]: OK done.
