### PR TITLE
fix(ssh): unable to pass a custom HostKeyCallback func

### LINKED ISSUE #411: git-ssh: try multiple algorithms for known_hosts
Hi,

When using git over ssh, it seems that if a host (eg: GitHub.com) has multiple keys (eg: an rsa and an ed25519 ones), but only one of those keys is listed in the `$HOME/.ssh/known_hosts`, and the one that's not listed has a higher preference (e.g. ed25519 over rsa), then the git clone operation will fail.

I feel it should try to be more intelligent and try to use the rsa one.

### PR DESCRIPTION
**Pull request by aymanbagabas**
Don't overwrite HostKeyCallback if one is provided.

Fixes: c35b8082c863 ("plumbing: transport/ssh, auto-populate ClientConfig.HostKeyAlgorithms. Fixes #411")
Fixes: https://github.com/go-git/go-git/issues/654
Signed-off-by: Ayman Bagabas <ayman.bagabas@gmail.com>

### CODE REVIEW

**Comment by mcuadros** [comment]
Can you provide some tests?

**Comment by aymanbagabas** [comment]
@mcuadros done!

**Comment by aymanbagabas** [comment]
@mcuadros any progress on this one?

**Comment by mcuadros** [comment]
@pjbgf

**Comment by pjbgf** [comment]
Manually tested this and can confirm it fixes the regression introduced by https://github.com/go-git/go-git/pull/548, which caused for `HostKeyCallback` to be ignored.

File: plumbing/transport/ssh/common_test.go [hunk 1]
```diff
@@ -93,12 +95,69 @@ func (s *SuiteCommon) TestDefaultSSHConfigWildcard(c *C) {
...
+}
+
+func (s *SuiteCommon) TestFailHostKeyCallback(c *C) {
+	uploadPack := &UploadPackSuite{
+		opts: []ssh.Option{
+			ssh.HostKeyPEM(testdata.PEMBytes["ed25519"]),
+		},
+	}
+	uploadPack.SetUpSuite(c)
+	// use the default client, which does not have a host key callback
```
Comment (pjbgf) [inline plumbing/transport/ssh/common_test.go:145]:
```suggestion
	// Use the default client, which does not have a host key callback.
```

File: plumbing/transport/ssh/common_test.go [hunk 2]
```diff
@@ -93,12 +95,69 @@ func (s *SuiteCommon) TestDefaultSSHConfigWildcard(c *C) {
...
+func (s *SuiteCommon) TestFixedHostKeyCallback(c *C) {
+	hostKey, err := stdssh.ParsePrivateKey(testdata.PEMBytes["ed25519"])
+	c.Assert(err, IsNil)
+	uploadPack := &UploadPackSuite{
+		opts: []ssh.Option{
+			ssh.HostKeyPEM(testdata.PEMBytes["ed25519"]),
+		},
+	}
+	uploadPack.SetUpSuite(c)
+	// use the default client, which does not have a host key callback
```
Comment (pjbgf) [inline plumbing/transport/ssh/common_test.go:126]:
```suggestion
	// Use the default client, which does not have a host key callback.
```

File: plumbing/transport/ssh/common_test.go [hunk 3]
```diff
@@ -93,12 +95,69 @@ func (s *SuiteCommon) TestDefaultSSHConfigWildcard(c *C) {
...
 }
 
+func (s *SuiteCommon) TestIgnoreHostKeyCallback(c *C) {
+	uploadPack := &UploadPackSuite{
+		opts: []ssh.Option{
+			ssh.HostKeyPEM(testdata.PEMBytes["ed25519"]),
+		},
+	}
+	uploadPack.SetUpSuite(c)
+	// use the default client, which does not have a host key callback
```
Comment (pjbgf) [inline plumbing/transport/ssh/common_test.go:105]:
```suggestion
	// Use the default client, which does not have a host key callback.
```

**Review by pjbgf — COMMENTED** [review]
A few nits, otherwise it looks good to me.

**Comment by aymanbagabas** [comment]
@pjbgf i updated the commit

**Review by pjbgf — APPROVED** [review]
@aymanbagabas thanks! :bow:
