### PR TITLE
plumbing: object, Fix timezone comparison in encode/decode tests.

### LINKED ISSUE #1755: Failing tests when running locally due to issue comparing commit who include time.Time
### Bug Description

When running `go test ./...` locally, I have two failing tests:
- TestCommitEncodeDecodeIdempotent
- TestTagEncodeDecodeIdempotent

The root cause is that the commit comparison are failing due to my timezone not being -07:00 . This fail when doing a deep s.Equal on the commit as time.Time comparison fail for testify when manipulating this type. See https://github.com/stretchr/testify/issues/1010 and https://github.com/stretchr/testify/issues/984 .

### go-git Version

v6 master

### Steps to Reproduce

Change your timezone and use latest golang compiler.

### Additional Information

I can easily make a PR that either change the s.Equal to a series of explicit Equal on selected field, or I can force the timezone of all commits to be UTC, or I can initialize the tests with the current timezone the tests are currently being run with. I have no idea which approach would be preferred.

### PR DESCRIPTION
**Pull request by Bluebugs**
Fixes #1755

time.Parse attaches a rich *time.Location from the system timezone database (with DST rules, named zones, transition tables), while Signature.Decode uses time.FixedZone which creates a minimal fixed-offset zone.

Use time.Unix with time.FixedZone to construct test timestamps that match exactly what the decode function produces, ensuring encode/decode idempotency tests compare equivalent timezone representations.

### CODE REVIEW

**Comment by cedric-appdirect** [comment]
This fix #1755

File: plumbing/object/tag_test.go [hunk 1]
```diff
@@ -180,8 +179,12 @@ func (s *TagSuite) TestTagDecodeWrongType() {
...
 
 func (s *TagSuite) TestTagEncodeDecodeIdempotent() {
-	ts, err := time.Parse(time.RFC3339, "2006-01-02T15:04:05-07:00")
-	s.NoError(err)
+	// Use time.Unix with a fixed zone to avoid timezone database differences.
+	// time.Parse would attach a rich Location from the system timezone database,
+	// but decode uses time.FixedZone which creates a minimal fixed-offset zone.
+	// Using Unix timestamp with FixedZone ensures encode/decode idempotency.
+	tz := time.FixedZone("", -7*60*60) // -07:00
+	ts := time.Unix(1136239445, 0).In(tz) // 2006-01-02T15:04:05-07:00
```
Comment (pjbgf) [inline plumbing/object/tag_test.go]: Instead, we can just change `time.Parse` for `time.ParseInLocation`:

```suggestion
	ts, err := time.ParseInLocation(time.RFC3339, "2006-01-02T15:04:05-07:00", time.UTC)
	s.NoError(err)
```
