### PR TITLE
*: clone, resolve relative local URLs against CWD in CloneOptions.Validate

### LINKED ISSUE #1723: v6: Clone of parent fails (worked in v5)
### Bug Description

Here is a test which shows the issue (works in v5 fails in v6):
```golang
func TestCloneParentDir(t *testing.T) {
	// clone parent directory to in-memory storage
	_, err := git.Clone(memory.NewStorage(), nil, &git.CloneOptions{
		URL: "../../",
	})
	require.NoError(t, err)
}
```

### go-git Version

v6.0.0-20251112161705-8cc3e21f07a9

### Steps to Reproduce

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AriehSchneier**
When a caller passes a URL like "../../some-repo" to Clone, the billy chroot-based FilesystemLoader rejects any path whose cleaned form starts with ".." ("chroot boundary crossed"), regardless of the chroot root.

Fix: in CloneOptions.Validate, detect local URLs whose cleaned form starts with ".." and resolve them to absolute paths via filepath.Abs before the URL reaches the transport layer. This matches the behaviour of `git clone`: relative paths are resolved against the caller's working directory at the command level, before any transport code runs.

Adds TestCloneOptionsValidate_RelativeDotDot as a regression test.

Note: This fix only applies to code paths that call CloneOptions.Validate (e.g., Repository.Clone). Direct calls to transport.NewEndpoint or transport.ParseURL will not have ../-relative paths normalized. A future PR may add normalization at the transport layer to cover all code paths.

Fixes: https://github.com/go-git/go-git/issues/1723

### CODE REVIEW

File: plumbing/transport/transport.go [hunk 1]
```diff
@@ -176,6 +177,17 @@ func parseFile(endpoint string) (*Endpoint, bool) {
 	}
 
 	path := endpoint
+	// Paths that navigate upward (e.g. "../../repo", "../sibling") would be
+	// rejected by the chroot-based filesystem loader with "chroot boundary
+	// crossed". Resolve them to absolute paths now, using the process's
+	// working directory, which is exactly what `git clone` does.
+	cleaned := filepath.Clean(path)
+	if !filepath.IsAbs(path) &&
+		(cleaned == ".." || strings.HasPrefix(cleaned, ".."+string(filepath.Separator))) {
```
Comment (pjbgf) [inline plumbing/transport/transport.go]: @AriehSchneier I'm under the impression this needs to be handled higher up the stack e.g. Clone/Open.

Comment (AriehSchneier) [reply plumbing/transport/transport.go]: I have moved it to `CloneOptions.Validate()` which fixes it in the `Clone` case (which is where I was hitting the error), but what if someone calls `transport.NewEndpoint()` directly it will no longer resolve.

**Comment by AriehSchneier** [comment]
@pjbgf any chance you can review this again, save me rebasing it any more...

(PS the windows fail would probably be fixed by #1999 or #2001)

File: plumbing/transport/transport.go (hunk 1 above)
Comment (pjbgf) [reply plumbing/transport/transport.go]: Overall, transport should enforce abs paths across the board so let's go ahead with the Clone fix for now.

File: options.go [hunk 2]
```diff
@@ -136,6 +138,20 @@ func (o *CloneOptions) Validate() error {
 		return ErrMissingURL
 	}
 
+	// Resolve ..-relative local paths to absolute paths before they reach
+	// the transport layer. The billy chroot-based FilesystemLoader rejects
+	// any path whose clean form starts with ".." with "chroot boundary
+	// crossed". Real git resolves such paths against the working directory
+	// at the command level, before any transport code runs.
+	if giturl.IsLocalEndpoint(o.URL) && !filepath.IsAbs(o.URL) {
```
[the remark this answers is not in the document]
Comment (AriehSchneier) [reply options.go:146]: Updated PR title/description

File: options.go [hunk 3]
```diff
@@ -136,6 +138,20 @@ func (o *CloneOptions) Validate() error {
...
+		cleaned := filepath.Clean(o.URL)
+		if cleaned == ".." || strings.HasPrefix(cleaned, ".."+string(filepath.Separator)) {
+			if abs, err := filepath.Abs(o.URL); err == nil {
+				o.URL = abs
+			}
```
[the remark this answers is not in the document]
Comment (AriehSchneier) [reply options.go]: Done

**Review by pjbgf — APPROVED** [review]
@AriehSchneier thanks for working on this. 🙇
