### PR TITLE
storage: dotgit, fix pack file permissions

### LINKED ISSUE #588: Cloning repo has unexpected packfile permissions
I am trying to use this to fetch sources to use in building packages for a Linux distribution, meaning that the cloned sources need to be copied, generally within a chroot with fakeroot.

Cloning a repo sets the pack file permissions in `.git/objects/pack` to `-rw-------`. When the packaging tool then tries to copy the cloned source to the work directory, it cannot because of missing permissions. Doing the same operation with `git` yields packfiles with read set for everyone.

Is this an issue with go-git, or am I doing something wrong?

```go
cloneOpts := git.CloneOptions{
    URL:               uri,
    Depth:             1,
    RecurseSubmodules: git.DefaultSubmoduleRecursionDepth,
    Progress:          os.Stdout,
}

git.PlainClone(clonePath, false, &cloneOpts)
```

This holds true in a simple test program that clones into /tmp without any elevated permissions. I am using version 5.4.2.

### PR DESCRIPTION
**Pull request by Ch00k**
Fixes #588

### CODE REVIEW

File: storage/filesystem/dotgit/writers_test.go [hunk 1]
```diff
@@ -161,3 +162,68 @@ func TestPackWriterUnusedNotify(t *testing.T) {
...
+	idxPath := fmt.Sprintf("objects/pack/pack-%s.idx", f.PackfileHash)
+	revPath := fmt.Sprintf("objects/pack/pack-%s.rev", f.PackfileHash)
+
+	stat, err := fs.Stat(pfPath)
+	require.NoError(t, err)
+	assert.Equal(t, os.FileMode(0o644), stat.Mode().Perm())
+
+	stat, err = fs.Stat(idxPath)
+	require.NoError(t, err)
+	assert.Equal(t, os.FileMode(0o644), stat.Mode().Perm())
```
Comment (pjbgf) [inline storage/filesystem/dotgit/writers_test.go]: The `0o644` permission does not seem to align with the upstream [code](https://github.com/git/git/blob/d8af7cadaa79d5837d73ec949e10b57dedb43e9b/builtin/index-pack.c#L1605) nor my observation of repos I cloned, which aligns with `0o444`:

Image

File: storage/filesystem/dotgit/writers_test.go [hunk 2]
```diff
@@ -161,3 +162,68 @@ func TestPackWriterUnusedNotify(t *testing.T) {
...
+	require.NoError(t, err)
+
+	_, err = w.Write([]byte("this is a test"))
+	require.NoError(t, err)
+
+	require.NoError(t, w.Close())
+
+	stat, err := fs.Stat("objects/a8/a940627d132695a9769df883f85992f0ff4a43")
+	require.NoError(t, err)
+	assert.Equal(t, os.FileMode(0o644), stat.Mode().Perm())
```
Comment (pjbgf) [inline storage/filesystem/dotgit/writers_test.go]: Same seems to be the case for loose objects.

File: storage/filesystem/dotgit/writers.go [hunk 3]
```diff
@@ -145,6 +147,7 @@ func (w *PackWriter) save() error {
 	if err := w.encodeIdx(idx); err != nil {
 		return err
 	}
+	fixPermissions(w.fs, fmt.Sprintf("%s.idx", base))
```
Comment (pjbgf) [inline storage/filesystem/dotgit/writers.go:154]: We probably should call this after the files are closed - this is likely what is breaking on Windows.

File: storage/filesystem/dotgit/writers_test.go [hunk 4]
```diff
@@ -161,3 +162,68 @@ func TestPackWriterUnusedNotify(t *testing.T) {
 
 	assert.NoError(t, w.Close())
 }
+
+func TestPackWriterPermissions(t *testing.T) {
+	t.Parallel()
+
+	if runtime.GOOS == "windows" {
+		t.Skip("not applicable to windows")
+	}
```
Comment (pjbgf) [inline storage/filesystem/dotgit/writers_test.go:171]: Can't we do the same for Windows?

```suggestion
```

File: storage/filesystem/dotgit/writers_test.go (hunk 1 above)
Comment (Ch00k) [reply storage/filesystem/dotgit/writers_test.go]: You are right, it should be 444.

Comment (Ch00k) [reply storage/filesystem/dotgit/writers_test.go]: Fixed

File: storage/filesystem/dotgit/writers_test.go (hunk 2 above)
Comment (Ch00k) [reply storage/filesystem/dotgit/writers_test.go]: Fixed

File: storage/filesystem/dotgit/writers.go (hunk 3 above)
Comment (Ch00k) [reply storage/filesystem/dotgit/writers.go:154]: Fixed

**Comment by Ch00k** [comment]
@pjbgf I did some more research on Windows, and came to a conclusion that fixing pack file permissions is not necessary there. This is what I found.

A fresh clonse of a repository with Git command line.

```powershell
PS C:\Users\aycp> git clone https://github.com/go-git/go-billy.git
Cloning into 'go-billy'...
remote: Enumerating objects: 2424, done.
remote: Counting objects: 100% (452/452), done.
remote: Compressing objects: 100% (183/183), done.
remote: Total 2424 (delta 369), reused 277 (delta 269), pack-reused 1972 (from 3)
Receiving objects: 100% (2424/2424), 665.80 KiB | 6.05 MiB/s, done.
Resolving deltas: 100% (1307/1307), done.
PS C:\Users\aycp>
PS C:\Users\aycp>
PS C:\Users\aycp> icacls .\go-billy\.git\objects\pack\*
.\go-billy\.git\objects\pack\pack-c7d2a28e9530e0dcab4b24de493ec350f7dff5de.idx NT AUTHORITY\SYSTEM:(I)(F)
                                                                               BUILTIN\Administrators:(I)(F)
                                                                               AYWIN\aycp:(I)(F)

.\go-billy\.git\objects\pack\pack-c7d2a28e9530e0dcab4b24de493ec350f7dff5de.pack NT AUTHORITY\SYSTEM:(I)(F)
                                                                                BUILTIN\Administrators:(I)(F)
                                                                                AYWIN\aycp:(I)(F)

.\go-billy\.git\objects\pack\pack-c7d2a28e9530e0dcab4b24de493ec350f7dff5de.rev NT AUTHORITY\SYSTEM:(I)(F)
                                                                               BUILTIN\Administrators:(I)(F)
                                                                               AYWIN\aycp:(I)(F)

Successfully processed 3 files; Failed processing 0 files
```

The `(I)(F)` means `Inherited` `Full Control`, which translates to 777 in Unix permission notation.

A fresh clone made with git-go:

```powershell
PS C:\Users\aycp> cat .\test_clone\go.mod
module test_clone

go 1.24.0

require github.com/go-git/go-git/v6 v6.0.0-20251223165309-e697feb6e2c6

require (
 github.com/Microsoft/go-winio v0.6.2 // indirect
 github.com/ProtonMail/go-crypto v1.3.0 // indirect
 github.com/cloudflare/circl v1.6.1 // indirect
 github.com/cyphar/filepath-securejoin v0.6.1 // indirect
 github.com/emirpasic/gods v1.18.1 // indirect
 github.com/go-git/gcfg/v2 v2.0.2 // indirect
 github.com/go-git/go-billy/v6 v6.0.0-20251209065551-8afc3eb64e4d // indirect
 github.com/golang/groupcache v0.0.0-20241129210726-2c02b8208cf8 // indirect
 github.com/kevinburke/ssh_config v1.4.0 // indirect
 github.com/klauspost/cpuid/v2 v2.3.0 // indirect
 github.com/pjbgf/sha1cd v0.5.0 // indirect
 github.com/sergi/go-diff v1.4.0 // indirect
 golang.org/x/crypto v0.46.0 // indirect
 golang.org/x/net v0.48.0 // indirect
 golang.org/x/sys v0.39.0 // indirect
)
PS C:\Users\aycp> cat .\test_clone\test_clone.go
package main

import (
    "github.com/go-git/go-git/v6"
)

func main() {
    git.PlainClone("go-billy", &git.CloneOptions{
        URL: "https://github.com/go-git/go-billy",
    })
}

PS C:\Users\aycp> .\test_clone\test_clone.exe
PS C:\Users\aycp> icacls .\go-billy\.git\objects\pack\*
.\go-billy\.git\objects\pack\pack-82e696cfc8152a8084420cc19f61fd4c63aa3fa0.idx NT AUTHORITY\SYSTEM:(I)(F)
                                                                               BUILTIN\Administrators:(I)(F)
                                                                               AYWIN\aycp:(I)(F)

.\go-billy\.git\objects\pack\pack-82e696cfc8152a8084420cc19f61fd4c63aa3fa0.pack NT AUTHORITY\SYSTEM:(I)(F)
                                                                                BUILTIN\Administrators:(I)(F)
                                                                                AYWIN\aycp:(I)(F)

.\go-billy\.git\objects\pack\pack-82e696cfc8152a8084420cc19f61fd4c63aa3fa0.rev NT AUTHORITY\SYSTEM:(I)(F)
                                                                               BUILTIN\Administrators:(I)(F)
                                                                               AYWIN\aycp:(I)(F)

Successfully processed 3 files; Failed processing 0 files
```

The permissions are the same as the ones made by Git command line.

In my opinion the code and tests in the current state is correct: we should not be executing `fixPermissions` if running on Windows.

**Comment by pjbgf** [comment]
@Ch00k thanks for the clarifications. Let's go ahead and get this merged so that it is improved for posix. In the future, perhaps some compatibility tests could be added to just ensure that permissions in go-git are consistently aligned with git across the different OSes.
